### ISSUE TITLE
chrome folder not created

### ISSUE THREAD

**Issue by acerov** [rmachielse/ember-cli-deploy-chrome-app#1]
Hi,

thanks for your addon.
I am new to ember-cli-deploy and after installing it and installing your addon "chrome" folder is not created as is explained in readme.
`npm install ember-cli-deploy-chrome-app` gave me 4 warnings:
`warn engine crx@3.0.3 wanted`
`warn deprecated lodash-node@2.4.1`
`warn deprecated deflate-crc32-stream@0.1.2`
`warn deprecated lodash@2.1.0`

my setup is:
ember: 1.13.8
node: 0.12.7
npm: 2.13.4
os: win32 x64

**Comment by rmachielse** [comment]
Hi @acerov 

You should do `ember install ember-cli-deploy-chrome-app` instead of `npm install ember-cli-deploy-chrome-app`. That will run the generation script as well. If you use `npm install` you have to run the generate script yourself by executing `ember g ember-cli-deploy-chrome-app`.

Thanks for letting me know, I'll update the readme accordingly!

**Comment by acerov** [comment]
@rmachielse that's it :thumbsup: thank you, updated readme will help newcomers

**Comment by acerov** [comment]
@rmachielse chrome folder is now generated but without "key.pem" file and `ember deploy production` give me errors because of nonexistent key.pem, contents of chrome folder is:
assets subfolder
background.js
manifest.json
window.html

**Comment by rmachielse** [comment]
@acerov I have identified the issue and pushed a new release (`0.1.3`). If you upgrade and re-run `ember g ember-cli-deploy-chrome-app` it will generate it.

**Comment by acerov** [comment]
@rmachielse I upgraded and did `ember g ember-cli-deploy-chrome-app` but there is still no key.pem

In the meantime I generated key.pem with `openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout key.pem -out cert.pem`
did `ember deploy production` and it gave me error "no URL provided for update.xml"

**Comment by rmachielse** [comment]
@acerov A key will only be generated if it doesn't exist yet, so if you remove or move the key you generated yourself it will generate a new one.

I pushed a new release again (`0.1.4`) that fixes the url error. Sorry for the trouble, it should be fixed now.

**Comment by acerov** [comment]
@rmachielse after deploy I got myappname.zip but when I install in chrome and run it I got just blank window. Sorry for thousand questions but it is how it is :)

**Comment by rmachielse** [comment]
@acerov Good to hear that the deploy is working! It's a bit hard to tell why your app remains blank, it's probably something specific to your application. Can you run the chrome app in development as described in the readme under usage? Does it work in that way? Do you see anything specific in the console?

There are some [known limitations](https://github.com/rmachielse/ember-cli-deploy-chrome-app#known-limitations). Are you aware of them?

**Comment by acerov** [comment]
@rmachielse yes I run it in development, in console I got:
`window.localStorage is not available in packaged apps. Use chrome.storage.local instead.`
so the show goes on :sweat_smile:

**Comment by rmachielse** [comment]
Ah yes, I've had that too. You'll have to make sure your application can handle that.

**Comment by acerov** [comment]
@rmachielse how did you handled that case?

**Comment by rmachielse** [comment]
@acerov By using `chrome.storage.local` in the chrome app
